apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: webapp
type: Opaque
data:
  database_user: {{ .Values.postgres.dbUser | b64enc }}
  database_password: {{ .Values.postgres.dbPassword | b64enc}}