apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: {{ .Values.webapp.service.type }}
  ports:
    - name: http
      port: {{ .Values.webapp.service.port }}
      targetPort: {{ .Values.webapp.service.targetPort }}